# -*- coding: utf-8 -*-
"""iris_prdiction_by_using_svm(SVC).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1esAOhMYn1Fcu-3QemnN-_L7IXsi60l
"""

!pip install numpy pandas matplotlib seaborn scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets
iris=datasets.load_iris()

iris = datasets.load_iris()

# Create DataFrame from iris data
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column (numeric labels)
df['flower'] = iris.target

# Map numeric labels to actual flower names
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['flower'], axis='columns'), df.flower, test_size=0.25)

from sklearn.svm import SVC
model = SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)

model.score(X_test, y_test)